version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.vue
    ports:
      - "3000:3000"
    command: npm run dev -- --host 0.0.0.0

  backend:    
    build:
      context: ./backend
      dockerfile: Dockerfile.golang
    env_file:
      - ./backend/config.yaml
    ports:
      - "8888:8888"
    container_name: backendsoal
    volumes:
      - ./backend:/app  
    depends_on:
      - frontend
      - db   
      - redis  


  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pg_database
    ports:
      - "5222:5432"
    volumes:
      - ./backend/dump.sql:/docker-entrypoint-initdb.d/dump.sql  
      - postgres-db:/var/lib/postgresql/data

  redis:  
    image: redis:alpine
    ports:
      - "6380:6379"  

volumes:
  postgres-db:
