# Start from the official Go image
FROM golang:1.23.1

# Set the current working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source code into the container
COPY . .

# Expose the app on port 8888
EXPOSE 8888

# Command to run the app using 'go run'
CMD ["go", "run", "main.go"]
